pychunkedgraph/backend/chunkedgraph.py, pychunkedgraph/edge_gen/Dockerfile, pychunkedgraph/edge_gen/edgetask.py, pychunkedgraph/edge_gen/requirements.txt
That's the version used for Pinky100. No performance improvements, yet.
=> feat(edge_gen): Initial PyChunkedGraph EdgeGen script

pychunkedgraph/backend/chunkedgraph.py
Extended `range_read_chunk` to allow the query of the latest root_ids to a specific point in time:
```
cg = ChunkedGraph(...)
root_rows = cg.range_read_chunk(cg.n_layers, 0, 0, 0, time_stamp=time_stamp, row_key_filters=[b'new_parents'])
```
=> improved range_read

pychunkedgraph/edge_gen/edgetask.py
fix: Always check for boundary supervoxel
fix: Potential issue with np.uint64 == int comparisons
performance: Skip Region Graph calculation on empty chunks
=> fix(edgegen): Always check for boundary SV

pychunkedgraph/meshing/meshgen.py
Modifies the `get_sv_to_node_mapping` function to include the connected supervoxel in the 1 vx overlap region, as well. This is required to precisely close the gaps between meshes of adjacent chunks. Also avoids weird "dust" floating around and reduces the number of triangles that is created.
=> fix(meshgen): Consistent meshes near chunk boundary

pychunkedgraph/app/cg_app_blueprint.py, pychunkedgraph/backend/chunkedgraph.py, pychunkedgraph/backend/exceptions.py, pychunkedgraph/tests/test.py, requirements.txt, setup.py, tox.ini
Travis fails because boost is missing - which is required by igneous, but I don't want to install igneous, or its C extensions or its dependencies for the tox tests... Would be happy if you have an idea how to get rid off igneous for the tests...
The tests itself are passing, but I changed a lot of the Flask stuff, which is not covered, yet... bit dangerous.
=> feat(core): slightly better error handling / feedback

Dockerfile
- installs pychunkedgraph (including igneous) using its own setup.py
=> fix(Dockerfile): igneous installation follows regular procedure

pychunkedgraph/app/cg_app_blueprint.py
Optional `timestamp` parameter for `/graph/root` endpoint.
Expects a unix timestamp (`float` or `int`, specifying the number of seconds since epoch), for example `/graph/root?timestamp=1540940003.4080591`
If none is specified, will default to the time when the server received the request.
=> feat(cg_app): timestamp for root endpoint

pychunkedgraph/meshing/meshgen_utils.py
Fetching the children of all missing nodes simultaneously, rather than one-by-one
=> performance(meshgen): faster mesh manifest generation

pychunkedgraph/meshing/Dockerfile, pychunkedgraph/meshing/meshgen.py
Switching to new graphene-style no static manifest meshing.
=> feat(meshgen.py): meshing w/o manifests

pychunkedgraph/backend/chunkedgraph.py, pychunkedgraph/backend/chunkedgraph_comp.py, pychunkedgraph/tests/test.py
first cut at implementing this feature.. would like a sanity check from others before cleaning it up. not intended to be merged yet.
=> added methods for getting only changed root ids between timestamps

pychunkedgraph/app/app_utils.py, pychunkedgraph/app/cg_app_blueprint.py, pychunkedgraph/app/meshing_app_blueprint.py, pychunkedgraph/backend/chunkedgraph.py, pychunkedgraph/logging/flask_log_db.py
- Removed deprecated frontend code.
- Implemented threading for meshing runs.
- Brought back performance logging in datastore
Non-blocking remeshing: A future / better solution will use something like celery (see #113). This is scheduled to come once the new meshing procedures are in place.
=> Changes to frontend

.dockerignore, .travis.yml, Dockerfile
* Added graph-tool to Dockerfile
* Run tests within Travis using same Dockerfile
=> Rework Dockerfile and Travis build for graph-tool

pychunkedgraph/backend/chunkedgraph.py
Read timestamp from lock row
--> rely on BigTable for clock sync
=> Resolved potential timestamp inconsistency

.gitignore, pychunkedgraph/app/app_utils.py, requirements.txt
Decorator to enable a function to respond on a pubsub connection
The decorator does 2 things:
* Create a client connection to given redis server url
* Publish the return value of the function on the given channel
The function is presumed to run on an external worker process managed by rq on a redis server
=> redis and rq job decorator

pychunkedgraph/backend/chunkedgraph.py, pychunkedgraph/backend/definitions/config.py, pychunkedgraph/ingest/__init__.py, pychunkedgraph/ingest/cli.py, pychunkedgraph/ingest/ingestion_utils.py, pychunkedgraph/ingest/ingestionmanager.py, pychunkedgraph/ingest/ran_ingestion_v2.py, pychunkedgraph/utils/redis.py
group related variables with named tuples
=> akhilesh-ingestion-manager-refactor

pychunkedgraph/meshing/meshgen_utils.py
When running the initial stitching after the initial meshing, if changes
have already been made to the proofreading, the range read of the chunk
to be stitched may contain node ids that share children. This was not
handled correctly by get_downstream_multi_child_nodes, now fixed.
=> Fix remeshing duplicate children bug

pychunkedgraph/app/segmentation/common.py
adds a missing line that caused split preview error
=> missing cg instance in api end point

pychunkedgraph/backend/chunkedgraph.py
One function to add a key-value pair; one to add many from a dictionary.
=> Create CG functions to add to dataset info

pychunkedgraph/app/app_utils.py, pychunkedgraph/app/meshing/legacy/routes.py, pychunkedgraph/app/meshing/v1/routes.py, pychunkedgraph/app/segmentation/common.py, pychunkedgraph/app/segmentation/generic/routes.py, pychunkedgraph/app/segmentation/legacy/routes.py, pychunkedgraph/app/segmentation/v1/routes.py, pychunkedgraph/graph_analysis/contact_sites.py, requirements.txt
among other things:
- latest middle auth support
- binary support for get roots
- better contact sites handling
=> Endpoints improvements

pychunkedgraph/app/segmentation/common.py, pychunkedgraph/backend/chunkedgraph.py
- added variables to info
- added stop layer parameter to roots calls
=> Further endpoint improvements

pychunkedgraph/app/meshing/common.py, pychunkedgraph/app/meshing/legacy/routes.py, pychunkedgraph/app/meshing/v1/routes.py, pychunkedgraph/app/segmentation/common.py, pychunkedgraph/app/segmentation/generic/routes.py, pychunkedgraph/app/segmentation/legacy/routes.py, pychunkedgraph/app/segmentation/v1/routes.py, requirements.txt
also: added `is_latest_roots` endpoint
=> Implemented configurable endpoints

pychunkedgraph/graph/utils/id_helpers.py
get_root crashes when trying get_root(0)
=> Ignore sv 0 when finding from coord

pychunkedgraph/app/meshing/common.py, pychunkedgraph/app/segmentation/common.py, rq_workers/mesh_worker.py
this is a clone of #218 but applied to the master branch.
=> Fcc mesh priority master

pychunkedgraph/app/meshing/common.py, pychunkedgraph/app/segmentation/common.py, rq_workers/mesh_worker.py
fixed bugs priority on queues.
=> Fcc mesh priority

pychunkedgraph/app/segmentation/common.py, pychunkedgraph/app/segmentation/v1/routes.py, pychunkedgraph/backend/chunkedgraph.py, pychunkedgraph/backend/graphoperation.py, pychunkedgraph/tests/test_graphoperation.py
Still work in progress, PRing this now for feedback
=> Add "get all user operations" and "rollback all user operations"

pychunkedgraph/backend/chunkedgraph.py
Master branch version of https://github.com/seung-lab/PyChunkedGraph/pull/223
=> bounding box param for more efficient leaves requests

pychunkedgraph/graph/edits.py
@manuel-castro told me about some failed edits, was able to run them with this fix, appears to be a skip connection issue when lower layer IDs are not included in connected components.
=> fix: failed edits due to skip connections

pychunkedgraph/app/segmentation/common.py
fixes bug reported by @manuel-castro
=> get roots fix

pychunkedgraph/app/segmentation/common.py, pychunkedgraph/app/segmentation/v1/routes.py, pychunkedgraph/graph_analysis/analysis.py
Here is the corresponding refactoring for master that mirrors #242 on minnie.
=> lvl2 graph endpoint for master

pychunkedgraph/graph_analysis/analysis.py
This is a mirror of #252 to save time in downloading and processing lvl2graph
=> only return unique lvl2id edges

pychunkedgraph/backend/history.py
fixing a typo bug in merge log
=> typo in merge log history

pychunkedgraph/app/segmentation/common.py, pychunkedgraph/backend/chunkedgraph.py, pychunkedgraph/backend/graphoperation.py
- Fix undo/redo chains
- Make parent_id optional for get_atomic_id_from_coord to allow supervoxel ID lookup from coordinate
- Make mincut optional for splits
=> Improvements to support edit porting

pychunkedgraph/app/segmentation/common.py, pychunkedgraph/backend/chunkedgraph.py
This is a mirror to #255 to add the same flag to the api, and normalize the behavior between the two versions.
=>  assert roots flag

pychunkedgraph/graph/cutting.py, pychunkedgraph/graph/utils/flatgraph.py
Update split logic to avoid "invalid vertex error". Now the shortest paths cannot include points on the opposing team's labeled points.
=> Mincut: path augment excludes other team

pychunkedgraph/app/segmentation/common.py
- add source and sink coords, so that it's still useful when there are no `added_edges` or `removed_edges`
- parse `operation_ids` as JSON list (per discussion in #267)
=> Improve operation details

pychunkedgraph/meshing/meshgen.py
Faulty np.where condition causing overlap voxels to be erroneously assigned to level 2 meshes
=> Remeshing flakes fix

pychunkedgraph/app/segmentation/common.py, pychunkedgraph/app/segmentation/v1/routes.py, pychunkedgraph/graph/chunkedgraph.py, pychunkedgraph/graph/operation.py
admin merge endpoint for nucleus soma mergers
=> admin merge precondition optional

pychunkedgraph/meshing/meshgen.py
Use `cv.mesh.get_meshes_on_bypass` instead of `cv.mesh.get` for improved parallelism/speed in downloading sharded meshes. Also use CloudFiles instead of cloudvolume.Storage in mesh generation.
=> Remeshing speedup and cleanup

pychunkedgraph/backend/chunkedgraph.py, pychunkedgraph/meshing/meshgen.py
Master branch version of https://github.com/seung-lab/PyChunkedGraph/pull/277
=> Remeshing flakes fix for master

pychunkedgraph/graph/meta.py, pychunkedgraph/graph/operation.py
* adds `READ_ONLY` flag in meta, useful for testing performance of edits without affecting the graph
* some formatting changes
=> read only flag

pychunkedgraph/io/edges.py
fixes incorrect use of cloudfiles that resulted in duplicate download requests
=> fix: incorrect cloudfiles usage

pychunkedgraph/app/segmentation/common.py
This bring this api call in line with the microns version.
=> leaves stop layer feature

pychunkedgraph/app/segmentation/common.py, pychunkedgraph/graph/misc.py
Discovered that this endpoint isn't working in Microns, here's my suggested fix. Haven't testing it fully yet.
=> fixing get_contact_sites

.gitignore, pychunkedgraph/app/segmentation/common.py, pychunkedgraph/app/segmentation/v1/routes.py, pychunkedgraph/backend/history.py, pychunkedgraph/backend/lineage.py
* multiple root IDs support for lineage graph extraction
* remove unused variables
=> feat: add support for multiple root IDs lineage graph

pychunkedgraph/meshing/meshgen.py
v1 version of https://github.com/seung-lab/PyChunkedGraph/pull/301
=> Fix: mesh stealing overlap bug

pychunkedgraph/app/segmentation/common.py
mirroring the commit i made for #314 I have refactored the timestamp parsing to be unified, and fixed what appears to be a missing feature in the is_latest call to be able to specify a timestamp for the is_latest.
=> Fcc timestamp parse

pychunkedgraph/app/segmentation/common.py, pychunkedgraph/graph/chunkedgraph.py
made is_latest_roots a function of the PCG and added timestamp conversion
=> added proper timestamp handling for is_latest_roots

pychunkedgraph/app/segmentation/common.py, pychunkedgraph/graph/chunkedgraph.py, pychunkedgraph/graph/edges/utils.py, pychunkedgraph/graph/edits.py, pychunkedgraph/graph/operation.py
Also create empty entries for undos of unsuccessful operations.
=> Use get_activated_edges in undo operation

pychunkedgraph/app/__init__.py, pychunkedgraph/app/app_utils.py, pychunkedgraph/app/config.py, pychunkedgraph/app/meshing/legacy/routes.py, pychunkedgraph/app/meshing/v1/routes.py, pychunkedgraph/app/segmentation/common.py, pychunkedgraph/app/segmentation/generic/routes.py, pychunkedgraph/app/segmentation/legacy/routes.py, pychunkedgraph/app/segmentation/v1/routes.py
This is a PR to discuss this feature which will allow for public release of datasets via a virtual table option which puts an upper bound on the timestamp parameters and node_ids that can be accessed in a table through a virtual table.
=> Virtual tables timestamp ceiling

pychunkedgraph/app/segmentation/common.py, pychunkedgraph/app/segmentation/v1/routes.py
adding delta roots to v1 (same as #325)
=> Delta roots v1

pychunkedgraph/app/segmentation/common.py, pychunkedgraph/app/segmentation/v1/routes.py
this adds an endpoint for delta roots... need to discuss if we need to wait for a new permission type to merge/deploy this.
=> adding delta roots endpoint

pychunkedgraph/app/__init__.py, pychunkedgraph/app/app_utils.py, pychunkedgraph/app/config.py, requirements.txt
to allow new table mapping code to function
=>  changes to how auth integrates to use new middle auth features

pychunkedgraph/graph/subgraph.py
v1 version of https://github.com/seung-lab/PyChunkedGraph/pull/341
=> fix: get_subgraph_nodes for supervoxel

pychunkedgraph/app/segmentation/common.py
Also fix missing is_priority in rollback
=> Add skip_operation_ids parameter to rollback

pychunkedgraph/graph_analysis/analysis.py
small segments like `720575940380805427` that fit within a single chunk do not have any cross edges which was causing numpy concatenate error
=> fix: use empty array for concatenate

cloudbuild.yaml
=> Dockerhub v2

cloudbuild.yaml
=> added dockerhub steps

Dockerfile
=> adding reqs to before source copy

README.md
Add some documentation explaining the required environmental parameters needed to connect to a pcg instance.
=> Add environmental parameter notes to ReadMe

pychunkedgraph/app/app_utils.py, pychunkedgraph/app/segmentation/common.py, pychunkedgraph/app/segmentation/v1/routes.py
- valid IDs
- user affiliation in tabular changelog
=> Added endpoint features

pychunkedgraph/backend/chunkedgraph.py
=> fixing pcgv1 delta roots

pychunkedgraph/app/segmentation/common.py, pychunkedgraph/graph/client/bigtable/client.py, pychunkedgraph/graph/client/bigtable/utils.py, uwsgi.ini
opening this as a discussion about how this should be structured... I think this is functional though perhaps a refactor should be thought about.
=> Pcgv2 user edit query

pychunkedgraph/app/app_utils.py
=> fix empty user ids

pychunkedgraph/backend/chunkedgraph.py
=> Fix is latest roots

pychunkedgraph/graph/cutting.py, pychunkedgraph/graph/utils/flatgraph.py
Change method of computing paths for split logic to improve performance via more specific stop criteria.
=> Split logic specifies all source/target pairs

pychunkedgraph/app/segmentation/common.py
Needed for showing splits and merges in user profiles.
=> Add is_merge to tabular_change_log_recent (pcgv2)

pychunkedgraph/app/segmentation/common.py
=> making timestamps on valid_nodes optional

pychunkedgraph/app/meshing/common.py, pychunkedgraph/meshing/manifest/__init__.py, pychunkedgraph/meshing/meshgen_utils.py, requirements.txt
=> fix: remove references to deprecated Storage

cloudbuild.yaml
Still need to test if that works
=> fix(cloudbuild.yaml): Adapt for multistage build

pychunkedgraph/io/edges.py, requirements.in, requirements.txt
@ranlu 's tests show  `multi_decompress_to_buffer` significantly improves decompression times for larger files.
=> fix: multithreaded decompression for larger chunk files

pychunkedgraph/io/edges.py
Temporary fix until https://github.com/protocolbuffers/protobuf/issues/10774 is resolved.
=> fix: explicit memoryview for protobuf

pychunkedgraph/ingest/cli.py, pychunkedgraph/io/edges.py
also adds support for running l2 chunk ingest locally
=> fix(ingest): handle empty input to parse_edges

override/supervisord.conf, uwsgi.ini
this will add the uwsgi stats server to the build
=> Uwsgi stats

override/supervisord.conf
adding stats server to v1 build
=> Uswsgi stats v1

pychunkedgraph/app/segmentation/common.py
=> fix(app): handle latest roots 0 timestamp issue
