pychunkedgraph/meshing/meshgen.py

`parallel = 8` might help meshing speed by downloading the segmentation chunks simultaneously.
`simplification_factor = 0` would skip the simplification step and thus keep the original Marching Cubes meshes with a ridiculously large number of triangles. Notably increases file size. Not enabled by default. Not recommended.
`cache_control` - sets the cache control tag for Mesh and Manifest files. Default is None (which I believe means `max-age=3600`)
Requires: https://github.com/seung-lab/igneous/pull/24

feat(meshgen): Faster Quick'n'Dirty Meshing

---

pychunkedgraph/app/__init__.py
pychunkedgraph/app/app_utils.py
pychunkedgraph/app/cg_app_blueprint.py
pychunkedgraph/app/config.py
pychunkedgraph/backend/chunkedgraph.py
pychunkedgraph/backend/chunkedgraph_comp.py
pychunkedgraph/backend/cutting.py
pychunkedgraph/meshing/meshgen.py
pychunkedgraph/tests/test.py
uwsgi.ini

Part of the large logging overhaul of the AnnotationFrameworkDeployment / PyChunkedGraph.
Problems this PR resolves / prepares to resolve:
- All debug print messages ended up as `ERROR` in Stackdriver.
- No easy way to tell which process/module reported which error
Details:
- Replaced `print` statements with logging (`ChunkedGraph` class, `cg_app_blueprint.py`, `tests.py`)
- ChunkedGraph initialization supports an optional `logger` argument
- If not specified, it will create a `{project_id}/{instance_id}/{table_id}` logger and a default `StreamHandler`
- `cg_app` creates a `ChunkedGraph` connection with its own `StreamHandler` + JSON formatting, which will be properly consumed by fluentd (see https://github.com/seung-lab/AnnotationFrameworkDeployment/pull/4)
Note:
- Had to disable …

refactor(logging): Use logging for app, core and core tests

---

pychunkedgraph/backend/chunkedgraph.py
pychunkedgraph/backend/cutting.py

- Fixes an issue where a mincut would fail because a connected component only contains sink points or only contains source points.
- Remove overly verbose log messages

refactor(mincut): simplify empty-cc check

---

pychunkedgraph/backend/chunkedgraph.py
pychunkedgraph/backend/chunkedgraph_utils.py
pychunkedgraph/tests/test.py

* `get_children` supports multiple nodes as input
* `_execute_read` takes care of splitting requests and uses Bigtables retry logic
* speedup for `get_subgraph_nodes`
* speedup for `get_subgraph_chunk`

performance(get_subgraph)

---

pychunkedgraph/app/cg_app_blueprint.py
pychunkedgraph/backend/chunkedgraph.py
pychunkedgraph/backend/utils/column_keys.py
pychunkedgraph/backend/utils/serializers.py
pychunkedgraph/meshing/meshgen_utils.py
pychunkedgraph/tests/test.py

Moved minimal required precomputed+graph information from the `info` object in CloudStorage to Bigtable. (Only `pinky100_sv16`, so far)
"minimal required" because we could/should also move the other graph-specific information (n_layer, fanout, chunk_size, etc.) into this info file to have everything in one location - but it's not urgent.
The Bigtable info file for `pinky100_sv16` now contains a field `data_dir` which is required for https://github.com/seung-lab/neuroglancer/pull/238

Store extended precomputed-style info in bigtable

---

pychunkedgraph/meshing/meshgen.py

* Uses `cg._cv_mesh_path` if no mesh directory is specified

fix(meshgen): Set default preview-mesh directory to ChunkedGraph mesh directory

---

pychunkedgraph/app/meshing_app_blueprint.py
pychunkedgraph/meshing/meshgen_utils.py

this adds an option to the meshing endpoint to only get meshes of an object within a certain spatial bounding box, this will speed up use cases of synapse meshes analysis to only need to download the fragments near the synapse.

adding a bounding box option to meshing endpoint

---

pychunkedgraph/backend/chunkedgraph.py

`ChunkedGraph._retrieve_connectivity` fetches three arrays of edge information for a row in BigTable and is designed to filter these arrays by whether or not the edges are connected. It seems like the `edges` array is properly filtered, but the other two (`affinities` and `areas`) are not when selecting disconnected edges. This leads to occasional crashes in `get_subgraph_chunk`, where the duplicate filtering assumes that these arrays are of the same length. 
This pull request implements a basic function to match the filtering operation across all three arrays.

bugfix: Filtering edge descriptors for disconnected edges

---

pychunkedgraph/backend/cutting.py
pychunkedgraph/tests/test.py

Check if mincut operation separates sources or sinks, if it does,
do not perform it and return a useful error to the user.
Also added associated unit test.

Raise exception when mincut separates sources or sinks

---

pychunkedgraph/app/__init__.py
pychunkedgraph/app/app_utils.py
pychunkedgraph/app/meshing/legacy/routes.py
pychunkedgraph/app/meshing/v1/routes.py
pychunkedgraph/app/segmentation/common.py
pychunkedgraph/app/segmentation/generic/routes.py
pychunkedgraph/app/segmentation/legacy/routes.py
pychunkedgraph/app/segmentation/v1/routes.py
requirements.txt

Addresses the remaining comments in #160 
Probably most interesting: an optional query string parameter `int64_as_str` that is understood by all current v1 endpoints. If specified, the JSONEncoder will recursively inspect and convert all occurrences of `np.int64` or `np.uint64` values to `str`.

Sync Neuroglancer with API v1

---

pychunkedgraph/app/segmentation/common.py
pychunkedgraph/app/segmentation/v1/routes.py
pychunkedgraph/backend/chunkedgraph.py
pychunkedgraph/backend/cutting.py

- Add split_preview endpoint
- Split_preview endpoint performs mincut calculation using graph-tool
- Returns connected components containing supervoxels. These are the components in the local graph that would result from removing the edges that the mincut calculation found
- There is no caching of the split. The user would have to perform a new mincut calculation to actually perform the split.
- Also refactored the graph-tool mincut from a monolithic function to a class with many modular functions

Split preview, and refactor graph-tool mincut

---

pychunkedgraph/backend/cutting.py

The remapping of the cross chunk edge supervoxels was missing in the split preview code, causing those supervoxels to be missing in the connected components returned by the split preview.

Fix: cross chunk edge split preview remapping

---

pychunkedgraph/graph_analysis/contact_sites.py

If the two roots given do not come close to each other an np.concatenate call will throw an error. This PR fixes this

Fix: pairwise contact sites breaks when two segments are far apart

---

pychunkedgraph/app/segmentation/common.py
pychunkedgraph/app/segmentation/v1/routes.py

For users of the ChunkedGraph who want to get the roots of several nodes at once, using `get_roots` is much more efficient than `get_root`

Add get_roots endpoint

---

Dockerfile

graph-tool installation methods have changed, so change them in the Dockerfile. Thanks to @nkemnitz for noticing the change of installation method.

graph-tool installation method change

---

pychunkedgraph/app/segmentation/common.py
pychunkedgraph/app/segmentation/v1/routes.py
pychunkedgraph/backend/chunkedgraph.py
pychunkedgraph/backend/history.py

Adds a `/tabular_change_log_weekly` page that returns all edits made in the past week (starting from the current time of day, 7 days ago) in a tabular form, for use in the Flywire leaderboard. It includes operation_id, timestamp, and user_id.
We might want to make this more flexible in the future to allow any start time, and maybe any end time, by taking those as parameters in the URL. If we do this the permission should probably be changed from `@auth_requires_permission("view")` to `@auth_requires_admin`, since it could get all edits like `/change_log` can.
If there's a better way to get all records for a given time than passing start_id=0 and end_id=max to `read_node_id_rows`, let me know, but it doesn't seem too slow in practice. Feedback on code structure/style is also welcome.

Weekly Tabular Changelog

---

pychunkedgraph/graph/cutting.py

Fixes the splitting error "Split failed: Need at least one array to concatenate"

splitting np concatenate error

---

pychunkedgraph/backend/cutting.py

Fixes the splitting error "Split failed: Need at least one array to concatenate"

splitting np.concat error

---

pychunkedgraph/app/meshing/common.py
pychunkedgraph/app/segmentation/common.py
rq_workers/mesh_worker.py

I've added an optional query parameter to split, merge, redo, undo.  priority=False, which defaults to True, but if False, will pass the priority onto the meshing service, which will change which redis queue this is placed in.  This will effectively prioritize priority=True (or priority omitted) requests, over priority=False requests.  Automated processes can use priority=False in order to make sure to prioritize human interactions over machine interactions in when things are remeshed.  This interface could be used in the future to extend into other parts of the system. 
I've also added 3 retries to the meshing jobs to cut down on the number of failed jobs, and made the retry period more aggressive for priority jobs vs non-priority jobs.

added mesh job priority feature

---

pychunkedgraph/app/segmentation/common.py
pychunkedgraph/app/segmentation/v1/routes.py
pychunkedgraph/graph/chunkedgraph.py
pychunkedgraph/graph/utils/generic.py

Refactored `get_subgraph` such that it requests the subgraph of several nodes at once as opposed to one at a time. For 20 nodes, observed 2-3x speedup during local testing. Also added endpoint so Neuroglancer can request the leaves of many nodes at a time. This will cut the number of http requests Neuroglancer has to make substantially when many segments are selected. Also fixed a minor bug in `get_subgraph` -- `return_layers` was not always respected when it was not [2] in the previous logic, because of skip connections (within the repo, it was always called with `return_layers = [2]`, so not a big deal).

Feat: faster get subgraph when requesting many nodes + many leaves endpoint

---

pychunkedgraph/app/segmentation/common.py
pychunkedgraph/app/segmentation/v1/routes.py
pychunkedgraph/graph/analysis/pathing.py

I'd like to open up the level2 graph used in the find_path tool to other applications.  We think we can use this to make very low resolution skeletons of neurons, and make a more dynamic proofreading process.
This PR breaks the level2 graph construction code in find path into another function, and then exposes that function via an api, and refactors the get_path code to call this new function. 
Assuming this restructuring makes sense and works, we can port this approach to the master version as well to keep the APIs at parity.

adding level2 graph get endpoint

---

pychunkedgraph/export/operation_logs.py
pychunkedgraph/export/to/datastore/__init__.py

datastore doesn't support large blobs, some splits can result in a large number of removed edges so these will be stored in a bucket, object identified by `operation_id`

feat: store removed edges in bucket

---

pychunkedgraph/graph/chunkedgraph.py
pychunkedgraph/meshing/meshgen.py

Instead of relying on `datetime.utcnow()` to produce the correct timestamp for remeshing, use the node_id's timestamp instead. Could possibly prevent instances of issue #239

use timestamp from node_id for remeshing

---

pychunkedgraph/graph/analysis/pathing.py

this saves time in the lvl2graph endpoint and also likely in the find path tool.  In tests graph downloading dropped from 17 to 14 seconds, and edge list size was cut by a factor of 91.

only return unique edges to save time processing

---

pychunkedgraph/app/segmentation/common.py

There are a small subset of supervoxels in minnie that are surrounded by id=0, which caused them to have no parents in the agglomeration graph, and thus calling get_roots on them fails to get a parent at the root level.  This in term causes cloud-volume to error when converting these blocks to a flat segmentation via a 503 error on the get_roots call triggered by agglomerate=True.  
This PR adds an optional flag "assert_roots" which defaults to True to enforce that all the roots must map to a rootID.  This was before being set to True only if asking for the stop_layer to be the top layer.. now you must be asking for the top_layer AND have assert_roots=True.  We are then free to change cloud-volume to use assert_roots=False by default, or as an option.   
I still need to test this out …

assert roots flag

---

pychunkedgraph/app/segmentation/common.py
pychunkedgraph/app/segmentation/v1/routes.py
pychunkedgraph/graph_analysis/analysis.py

Add flag to find_path that enables a coarse path to be returned (one that does not require meshes).  This functionality already exists in the minnie branch.

Add find_path coarse precision

---

pychunkedgraph/meshing/meshgen.py
pychunkedgraph/meshing/meshgen_utils.py
pychunkedgraph/meshing/meshing_batch.py
pychunkedgraph/meshing/meshing_sqs.py
requirements.txt

Meshing creates a CV instance to retrieve meshes and mesh-related info. That CV instance currently points to the CG Server, but that is unnecessary, as we can simply pass the info file in instead.

Removing meshing's reliance on CG Server

---

pychunkedgraph/app/segmentation/common.py

#265. Passing on the timestamp will effectively declare root ids as latest when there has not been an edit to this root id before the provided timestamp.

passing timestamp to bigtable call

---

pychunkedgraph/graph/cutting.py
pychunkedgraph/graph/utils/flatgraph.py
pychunkedgraph/tests/test_uncategorized.py

This PR makes three changes to the split algorithm to fix bugs and improve robustness.
1) I now catch a case where a zero-length list was passed to a graph_tool function which couldn't handle it, which fixes the `Invalid type for edge list` error.
2) When paths overlap, I perform one additional fallback. If giving the overlap region to one team causes there to be no paths for between labeled points of the other team, I swap ownership of the overlap region and try one last time before raising an error.
3) I improved the logic for isolating cuts so that they are now allowed in only the case that all edges from the cut region are onto nodes from the initial set of labels : I.e. if blue is going to be an isolated split, all adjacent supervoxels on the other side must be human-labeled. This …

Csm mincut robustness fix

---

pychunkedgraph/graph/cutting.py
pychunkedgraph/graph/utils/flatgraph.py

This fixes an infinite recursion error introduced in the last update that could occur in conditions where absolutely no non-overlapping paths could be found.

Csm mincut assertion fallback fix

---

Dockerfile
requirements.txt

The new pip resolver breaks with cloud-files>=1.25.2. Downgrading pip to 20.2 worked but we should not use it for long. tbh, we did not see another way out of this.

Fixing dependency issues

---

pychunkedgraph/app/segmentation/common.py
pychunkedgraph/app/segmentation/v1/routes.py
pychunkedgraph/graph/chunkedgraph.py
pychunkedgraph/graph/operation.py
pychunkedgraph/graph/utils/id_helpers.py

Porting over the changes I made to v1. These are in master PRs #191, #212, #260, #267, #270, and #271. The code is almost identical, just had to change `cg.read_log_rows` to `cg.client.read_log_entries`.
The only additional changes are:
- a fix to `handle_undo` and `handle_redo` in `common.py`, to call `cg.undo_operation` and `cg.redo_operation` instead of the nonexistent `cg.undo` and `cg.redo`.
- add `added_edges` and `removed_edges` to the log entries for undo and redo operations as appropriate, so that you don't have to look up the undone/redone operation to find them.
These changes may get added to v1 separately.

Training changes ported to v2

---

pychunkedgraph/app/segmentation/common.py
pychunkedgraph/graph/analysis/pathing.py
pychunkedgraph/graph/chunkedgraph.py
pychunkedgraph/graph/utils/id_helpers.py
pychunkedgraph/meshing/mesh_analysis.py

Fixes #296. Also fixes an additional bug I noticed: find path was not working for roots where `cg.get_root(sv_id) != root_id` for a selected `(root_id, sv_id)` pair in neuroglancer.  This is fixed by taking into account a root's initial timestamp in the `get_atomic_id_from_coord` function. This second bug is also existent in V1, so I will create a separate PR for that.

Fix: v2 find path precision mode 

---

docs/Readme.md
pychunkedgraph/graph/chunks/utils.py
pychunkedgraph/graph/misc.py
pychunkedgraph/meshing/manifest/sharded.py

the bbox vs bounding_box argument names between the two versions is killing us here in keeping these versions synced... I just made the same mistake on master.

bugfix: typo on argument name

---

pychunkedgraph/meshing/meshgen.py

Currently, when the mesh generation code generates meshes for a set of L2 ids in a chunk, it checks which of those L2 ids are connected in the overlap region, and maps all connected L2 ids to a single id. The result can look something like this:
This change only maps the overlap region to a single id, keeping the L2 ids within the chunk to be mapped to their own id. Here's what this example looks like after the change:

Fix: mesh stealing bug

---

pychunkedgraph/app/segmentation/common.py
pychunkedgraph/app/segmentation/v1/routes.py
pychunkedgraph/backend/chunkedgraph.py
pychunkedgraph/backend/chunkedgraph_utils.py
pychunkedgraph/backend/utils/misc_utils.py
pychunkedgraph/tests/test_uncategorized.py

This functionality already exists in v2, here I've ported it to v1 (see: https://github.com/seung-lab/PyChunkedGraph/pull/228)
Add endpoint leaves_many that takes many node_ids and returns a dictionary of nodes to leaves to the user. Add new function `_get_subgraph_multiple_nodes` which replaces `_get_subgraph_higher_layer_nodes` and can take more than one node_id -- the advantage is that the leaves of the requested nodes can be requested at the same time, instead of calling the function multiple times. This means we can receive a big performance boost when retrieving leaves of multiple nodes, since we only have to make roughly` n_layers` requests to BigTable instead of `n_layers * n_nodes`. Right now the ChunkedGraph does not request leaves of multiple roots, but one clear applicable …

Feat: Request nodes and/or leaves of many roots efficiently

---

pychunkedgraph/app/app_utils.py
pychunkedgraph/app/segmentation/common.py
pychunkedgraph/backend/chunkedgraph.py

This PR is overhauling how supervoxel ids are derived from coordinates (and a parent id). Currently, we are seeing many errors because supervoxel ids cannot be found. The new approach supports parallel lookup of many coordinates and heuristically groups coordinates before lookups. It is more robust against failures by iterating through a list of maximal allowable distances. Tested on the fly sandbox and it works well.

Improved supervoxel lookup

---

pychunkedgraph/app/segmentation/common.py
pychunkedgraph/graph/client/bigtable/__init__.py
pychunkedgraph/graph/client/bigtable/client.py
pychunkedgraph/tests/helpers.py

This adds a configuration for max_row_count in the bigtable client (and changes the default to 1000).
It also has a fix for get_leaves with stop_layer which was not working becuase the format wasn't consisstent in unpacking the resullts of the bigtable query.  Using the flatten option simplified thing.  One can look up what level things are from via the nodeId.

get leaves fix + configurable row count

---

pychunkedgraph/app/segmentation/common.py
pychunkedgraph/app/segmentation/v1/routes.py

The rollback uses all_user_operations, so this will cause them to be skipped in the rollback as well (allowing for multiple rollbacks if one throws an error).

Don't include undone operations in all_user_operations

---

requirements.txt

to allow for the new tablemapping code to function

bumping middle auth client

---

pychunkedgraph/app/app_utils.py
pychunkedgraph/app/segmentation/v1/routes.py

The timestamp capping wasn't working when a timestamp was passed, and remap public was missing from some new endpoints.

Remap public fixes

---

pychunkedgraph/backend/chunkedgraph.py

Currently `get_children` returns an empty array for supervoxels which causes `mask_nodes_by_bounding_box` to crash

fix: get_subgraph_nodes for supervoxel

---

pychunkedgraph/graph/operation.py

Previously they had used the status of the undone/redone entry (which is not what we need here). Now it uses the status of the undo/redo itself.

Fix operation status and exception in undo/redo log entries

---

pychunkedgraph/meshing/meshgen.py

meshing code already handles missing roots as a result of failed/killed ingest tasks and masks them out

fix: use fail_to_zero=True in for initial meshing

---

pychunkedgraph/debug/cross_edge_test.py
pychunkedgraph/debug/existence_test.py
pychunkedgraph/debug/family_test.py
pychunkedgraph/graph/edits.py

I think this solves a bug with doing merges that include skip connections, we don't want to be reassigning parents of lower level ids in the new parents run, so when including those skip connection edges, we need to remap any edges discovered in this way from the lower IDs to their appropriate parent at the current level of the hierarchy.

fixing merge with skip connections

---

pychunkedgraph/app/segmentation/common.py

should make endpoint work with no passed timestamps where it presently errors as timestamp range is identical

allowing valid nodes timestamp to be None

---

pychunkedgraph/graph/edges/__init__.py

Proposed changes:
* only set `self._affinities` and `self._areas` if they are not provided
* `np.array(` will only create copies if necessary (e.g. because the data type is not what it should be)
The second one might be a bit risky? Depending on what the original, intended behavior was: the default behavior for `np.array` in `__init__` is to always create a copy, but the current setters are only updating the reference

performance: Edge initialization

---

Dockerfile
cloudbuild.yaml
requirements.yml

Using Kaniko for caching intermediary layers between builds... but it's not great. The constant snapshot taking of the entire file system for caching purposes also makes it quite slow.
Kaniko also didn't understand my multistage Dockerfile (or I missed a setting), so for now  I switched to let it build the entire Dockerfile step-by-step. If cbtemulator really is not necessary, maybe a second Dockerfile for cloudbuild is a good idea...

deps: switch to pinned dependencies for production

---

pychunkedgraph/app/__init__.py
pychunkedgraph/app/app_utils.py
pychunkedgraph/app/common.py

* Py3.10: [traceback.print_exception(exc, /, [value, tb, ]limit=None, file=None, chain=True)](https://docs.python.org/3.10/library/traceback.html#traceback.print_exception)
* Flask: `app.json_encoder`, `JSONIFY_MIMETYPE`, and `JSONIFY_PRETTYPRINT_REGULAR` were removed in 2.3.0. Now using the new `JSONProvider` interface introduced in [flask 2.2.0](https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-2-0)

Python 3.11 migrations

---

pychunkedgraph/meshing/meshgen.py
pychunkedgraph/meshing/meshgen_utils.py

* nonhomogeneous ndarray creation requires `dtype=object`
* zmesh fixed transpose bug - no need for additional transpose

More Python 3.11 + dependency upgrade related stuff

---

pychunkedgraph/app/segmentation/common.py

I am guessing this is the cause of https://github.com/seung-lab/CAVEclient/issues/120
Not sure how to test...

Correctly return response in `valid_nodes`

---

pychunkedgraph/app/segmentation/common.py
pychunkedgraph/app/segmentation/v1/routes.py
pychunkedgraph/graph/analysis/pathing.py

Client-side companion PR: https://github.com/seung-lab/CAVEclient/pull/154

Add bounding box argument to level 2 chunk graph endpoint

---

pychunkedgraph/app/meshing/common.py

since the existing use of the body is not in the http spec
left the body override in since it is used by cloud-volume and possibly more

fix(manifest): allow overriding start layer using query parameter
